### PR TITLE
fix(just): fix regenerate-grub just script

### PR DESCRIPTION
**Pull request by fiftydinar**
It doesn't account for UEFI vs BIOS systems, so fix that.

### CODE REVIEW

**Comment by fiftydinar** [comment]
Umm, reopen please

**Comment by fiftydinar** [comment]
Or merge it haha

**Comment by KyleGospo** [comment]
> Umm, reopen please

head repo is deleted, I'm not able to reopen or merge it, but I could take your changes and commit them manually

**Comment by fiftydinar** [comment]
> > Umm, reopen please
> 
> head repo is deleted, I'm not able to reopen or merge it, but I could take your changes and commit them manually

Sounds good

**Comment by KyleGospo** [comment]
Merged as https://github.com/ublue-os/config/commit/4b0bddda8e9e5b8796ec0c0a9fc867c0b564a7bc

**Pull request closed without merging**
