### PR TITLE
fix: Use import for just

### LINKED ISSUE #178: Migrate justfiles to import
https://github.com/casey/just/pull/1779

Just 1.18.x is headed to Fedora soon, I got pinged by the Fedora maintainer with this heads up. Looks like we need to move to `!import` instead of `!include` and then probably swap it out in the `~/.justfile`.

A nice bonus is the feature is stable! cc @ublue-os/approver @ublue-os/member

### PR DESCRIPTION
**Pull request by KyleGospo**
Fixes #178

### CODE REVIEW

**Comment by castrojo** [comment]
This one will be critical so let's take our time testing this one!

**Comment by castrojo** [comment]
This is tracking the `just` update in Fedora, so we should time it when it lands: https://bodhi.fedoraproject.org/updates/FEDORA-2023-4bdb1708ac

**Comment by ragazenta** [comment]
Emm, sorry but it should be `import` (without `!`)

**Comment by KyleGospo** [comment]
> Emm, sorry but it should be `import` (without `!`) and should use quote for path.

Thanks, that should be corrected now.

**Comment by castrojo** [comment]
Here's all the places we use [just --unstable](https://github.com/search?q=repo%3Aublue-os%2Fconfig+--unstable&type=code), we should probably clean all this up?

**Comment by p5** [comment]
> Here's all the places we use [just --unstable](https://github.com/search?q=repo%3Aublue-os%2Fconfig+--unstable&type=code), we should probably clean all this up?

@castrojo 
Completed in [299ed11](https://github.com/ublue-os/config/pull/179/commits/299ed11eb44b8c15cced46754ac9ef704cd697aa)

I kept `ujust` because I feel the `u` may stand for "unstable"?  Otherwise there's not much point in `ujust`

**Review by EyeCantCU — APPROVED** [review]
Everything here looks good! 1.18.1 just landed in the main images

**Comment by castrojo** [comment]
We should just drop ujust as a verb now that we have this. Though that, is a fight for another day lol!

**Review by castrojo — APPROVED** [review]

**Pull request merged**
