### PR TITLE
feat: update game devices repo

### PR DESCRIPTION
**Pull request by castrojo**
jntesteves recommends using this repo instead of his.

### CODE REVIEW

**Comment by castrojo** [comment]
We need to confirm the rules end up in the same place.

**Comment by bsherman** [comment]
Looks like this may need a minor change to work. The tarballs extract to different paths by default.

**Review by bsherman — APPROVED** [review]
Tested locally to validate this change. Looks like it's working well!

**Comment by awebeer256** [comment]
> jntesteves recommends using this repo instead of his.

Where does he say this?

**Comment by awebeer256** [comment]
Paging @castrojo ^

**Comment by castrojo** [comment]
What's the issue? This was merged?

**Comment by awebeer256** [comment]
Where does jntesteves say that he recommends using this other repo instead of his own?

**Comment by castrojo** [comment]
In discord, sorry I was on mobile and skipped past the collapsed part of the thread.

**Pull request merged**
