### PR TITLE
Attempt to fix "Temporary failure in name resolution"

### PR DESCRIPTION
**Pull request by fiftydinar**
in automatic rpm-ostree update script incorporating @bsherman changes.

Not sure if systemd preset is needed as the service is already enabled by default I believe.

Issue:
https://github.com/ublue-os/config/issues/90

### CODE REVIEW

**Review by bsherman — CHANGES_REQUESTED** [review]
I appreciate the help but unless I'm  mistaken, 'rpm-ostreed-automatic.service' is the service requiring improvement, not 'rpm-ostreed.service'.

**Comment by fiftydinar** [comment]
> I appreciate the help but unless I'm mistaken, 'rpm-ostreed-automatic.service' is the service requiring improvement, not 'rpm-ostreed.service'.

You are right, I made a mistake

**Comment by bsherman** [comment]
No worries! You can close this PR or just submit the updates you'd like to this PR and I'll be happy to review again.

**Comment by fiftydinar** [comment]
> No worries! You can close this PR or just submit the updates you'd like to this PR and I'll be happy to review again.

I followed "Add more commits by pushing to the [fiftydinar-patch-1](https://github.com/fiftydinar/config/tree/fiftydinar-patch-1) branch on [fiftydinar/config](https://github.com/fiftydinar/config)"

but it made a separate PR. I wanted to make all into 1 PR for it to be clean, but well. I have to learn better.

Here's the final PR:
https://github.com/ublue-os/config/pull/93

**Comment by fiftydinar** [comment]
This can be closed.

**Pull request closed without merging**
