### PR TITLE
feat(just): verbose and quiet update messages

### PR DESCRIPTION
**Pull request by bmp**
Verbose output with just disable-updates and prompts to update each command

### CODE REVIEW

**Review by bsherman — APPROVED** [review]
I did some testing with this and it looks nice.

Thank you for the submission!

**Comment by bmp** [comment]
@bsherman It continues to say merging is blocked, do I need to do anything else?

**Comment by bsherman** [comment]
> @bsherman It continues to say merging is blocked, do I need to do anything else?

It can be merged after another member of the approval team gives approval.

**Comment by bsherman** [comment]
Oh, also @bmp ... can  you modify your commit message to be semantic?

Instead of "Update 10-update.just" make it something like "feat(just): verbose and quiet update messages"

**Comment by bmp** [comment]
> Oh, also @bmp ... can you modify your commit message to be semantic?
> 
> Instead of "Update 10-update.just" make it something like "feat(just): verbose and quiet update messages"

Done, made the change, is there a guide somewhere that I could read about appropriate commit messages?

**Comment by bmp** [comment]
@bsherman Thank you for the tips, I have made the changes and pushed the commit onto my repo. It seems like it passed Semantic PR check now :-). Now it needs another reviewer to approve I guess.

**Comment by bsherman** [comment]
> Thank you for the tips,

You're welcome! Thanks for making the changes! I've asked some others to take a look.

**Review by akdev1l — APPROVED** [review]

**Pull request merged**
