### PR TITLE
feat(distrobox): Add Bluefin CLI & Wolfi (DX)

### PR DESCRIPTION
**Pull request by EyeCantCU**
Allows users to assemble Bluefin CLI and Wolfi distrobox images

### CODE REVIEW

**Review by castrojo — APPROVED** [review]

**Review by bsherman — CHANGES_REQUESTED** [review]
@EyeCantCU shouldn't this include an rpm spec version bump?

**Comment by EyeCantCU** [comment]
> @EyeCantCU shouldn't this include an rpm spec version bump?

Yup. Will get that up

**Comment by bsherman** [comment]
@EyeCantCU force pushing burned you here

You need to merge from `main` branch to get updates... you are a few versions behind on that spec version.

**Comment by EyeCantCU** [comment]
Thanks for the heads up :). Rebased my changes

**Review by bsherman — APPROVED** [review]

**Pull request merged**
