### PR TITLE
feat: add udev rules for linksys ae1200 usb wifi dongle

### PR DESCRIPTION
**Pull request by another-sapiens**

### CODE REVIEW

**Review by HikariKnight — APPROVED** [review]

**Comment by HikariKnight** [comment]
this is the original comment from the original PR #212 

> Provides support for the Linksys AE1200, a USB dongle that enables WiFi.
> 
> Essentially, on normal distros the dongle does not work on boot. It must be physically disconnected and plugged back in to be recognized. Upon closer examination, there seems to be a mismatch between the device ID on boot (13b1:0bdc) and the value that brcmfmac (the kernel module) accepts (13b1:0039). After physically plugging it for the 2nd time, lsusb states the correct ID.
> 
> Having this udev rule fixes the issue and WiFi works on boot. Merging this would remove the need to keep the spare .rules file.
>

**Comment by another-sapiens** [comment]
Github says "this branch is out-of-date with the base". Should I press the button that says "update branch"?

**Comment by HikariKnight** [comment]
> Github says "this branch is out-of-date with the base". Should I press the button that says "update branch", @HikariKnight ?

did it for you, been trying to poke people about this PR but people have been busy and are still very busy

**Comment by another-sapiens** [comment]
> did it for you, been trying to poke people about this PR but people have been busy and are still very busy

Ah, thank you  :)
Don't worry, there's no rush with this PR. It's easy for the user to paste the fix on their system in the meantime.

**Review by KyleGospo — APPROVED** [review]

**Pull request merged**
